name: Docker Build

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:

  # This workflow contains a single job called "build"
  docker-build:
    name: Docker build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
      - name: Build and push latest
        id: docker_build_and_push_latest
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: sparebank1utvikling/ora2pg:latest
      - name: Build and push tag
        id: docker_build_and_push_tag
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: sparebank1utvikling/ora2pg:${{github.ref_name}}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
